// packages/magus-typescript-viewer/src/client/components/DependencyGraph/components/GraphSearch.vue
<script setup lang="ts">
import { ref } from 'vue';

import type { DependencyNode, GraphEdge, SearchResult } from '../types';

interface GraphSearchProps {
  nodes: DependencyNode[];
  edges: GraphEdge[];
}

const props = defineProps<GraphSearchProps>();
const emit = defineEmits<{
  'search-result': [result: SearchResult];
}>();

const searchQuery = ref('');

const handleSearch = () => {
  if (!searchQuery.value) {
    emit('search-result', { nodes: [], edges: [], path: [] });
    return;
  }

  const matchingNodes = props.nodes.filter((node) =>
    node.data?.label.toLowerCase().includes(searchQuery.value.toLowerCase())
  );

  const matchingNodeIds = new Set(matchingNodes.map((n) => n.data.id));

  const relatedEdges = props.edges.filter(
    (edge) => matchingNodeIds.has(edge.data.source) || matchingNodeIds.has(edge.data.target)
  );

  emit('search-result', {
    nodes: matchingNodes,
    edges: relatedEdges,
    path: matchingNodes,
  });
};

const handleKeyDown = (event: KeyboardEvent) => {
  if (event.key === 'Enter') {
    handleSearch();
  }
};

const handleClear = () => {
  searchQuery.value = '';
  emit('search-result', { nodes: [], edges: [], path: [] });
};
</script>

<template>
  <div class="flex gap-2 bg-background-paper p-2 rounded-lg border border-gray-700 shadow-lg">
    <input
      v-model="searchQuery"
      type="text"
      placeholder="Search nodes..."
      @keydown="handleKeyDown"
      class="px-3 py-1 bg-gray-800 text-white rounded border border-gray-600 focus:outline-none focus:border-blue-500 transition-colors"
      aria-label="Search graph nodes"
    />
    <button
      @click="handleSearch"
      class="px-3 py-1 bg-gray-700 text-white rounded hover:bg-gray-600 transition-colors border border-gray-600"
      aria-label="Execute search"
    >
      Search
    </button>
    <button
      v-if="searchQuery"
      @click="handleClear"
      class="px-2 py-1 bg-red-700 text-white rounded hover:bg-red-600 transition-colors border border-red-600"
      aria-label="Clear search"
    >
      ×
    </button>
  </div>
</template>

// packages/magus-typescript-viewer/src/client/components/DependencyGraph/components/GraphSearch.tsx
import { useCallback, useState } from 'react';

import { Box, Button, TextField } from '@mui/material';
import { Panel } from '@xyflow/react';

import { graphSearchStyles } from '../../../theme/graphTheme';

import type { Edge } from '@xyflow/react';
import type { JSX } from 'react';

import type { DependencyNode } from '../types';

interface GraphSearchProps {
  nodes: DependencyNode[];
  edges: Edge[];
  onSearchResult?: (result: SearchResult) => void;
}

interface SearchResult {
  nodes: DependencyNode[];
  edges: Edge[];
  path?: DependencyNode[];
}

export function GraphSearch({ nodes, edges, onSearchResult }: GraphSearchProps): JSX.Element {
  const [searchQuery, setSearchQuery] = useState('');

  const handleSearch = useCallback(() => {
    if (!searchQuery) {
      onSearchResult?.({ nodes: [], edges: [], path: [] });
      return;
    }

    const matchingNodes = nodes.filter((node) => node.data.label.toLowerCase().includes(searchQuery.toLowerCase()));

    const relatedEdges = edges.filter((edge) =>
      matchingNodes.some((node) => node.id === edge.source || node.id === edge.target)
    );

    onSearchResult?.({
      nodes: matchingNodes,
      edges: relatedEdges,
      path: matchingNodes,
    });
  }, [searchQuery, nodes, edges, onSearchResult]);

  const handleKeyDown = useCallback(
    (event: React.KeyboardEvent) => {
      if (event.key === 'Enter') {
        handleSearch();
      }
    },
    [handleSearch]
  );

  return (
    <Panel position="top-left">
      <Box sx={graphSearchStyles.container}>
        <TextField
          size="small"
          placeholder="Search nodes..."
          value={searchQuery}
          onChange={(e) => {
            setSearchQuery(e.target.value);
          }}
          onKeyDown={handleKeyDown}
          sx={graphSearchStyles.input}
        />
        <Button variant="outlined" size="small" onClick={handleSearch} sx={graphSearchStyles.button}>
          Search
        </Button>
      </Box>
    </Panel>
  );
}
