// packages/lbh-typescript-viewer/src/client/components/DependencyGraph/nodes/DependencyNode.tsx
import { memo, useCallback } from 'react';

import { styled, useTheme } from '@mui/material/styles';
import { Handle, NodeResizer, Position, useReactFlow } from '@xyflow/react';

import { graphTheme } from '../../../theme/graphTheme';

import type { Theme } from '@mui/material/styles';

import type { DependencyData, DependencyKind, DependencyProps, NodeMethod, NodeProperty } from '../types';

const NodeContainer = styled('div')<{ selected: boolean; type: string }>(
  ({ theme, selected, type }: { theme: Theme; selected: boolean; type: string }) => ({
    padding: `${String(graphTheme.nodes.padding.header)}px ${String(graphTheme.nodes.padding.content)}px`,
    borderRadius: graphTheme.nodes.borderRadius,
    backgroundColor: graphTheme.nodes.colors.background.default,
    border: `1px solid ${selected ? theme.palette.primary.main : graphTheme.nodes.colors.border}`,
    minWidth: graphTheme.nodes.minDimensions.width,
    minHeight: graphTheme.nodes.minDimensions.height,
    boxShadow: selected ? `0 0 0 1px rgba(144, 202, 249, 0.5)` : 'none',
    fontSize: type === 'package' ? '14px' : '12px',
    position: 'relative',
    cursor: 'move',
    zIndex: type === 'package' ? 5 : 1,
    color: theme.palette.common.white,
    transition: 'all 0.2s ease',
    width: 'auto',
    height: 'auto',
    '&:hover': {
      backgroundColor: graphTheme.nodes.colors.background.package,
      border: `1px solid ${selected ? theme.palette.primary.main : graphTheme.nodes.colors.border}`,
    },
  })
);

const NodeHeader = styled('div')(({ theme }: { theme: Theme }) => ({
  marginBottom: theme.spacing(0.5),
  display: 'flex',
  alignItems: 'center',
  gap: theme.spacing(0.5),
  borderBottom: `1px solid ${graphTheme.nodes.colors.border}`,
  paddingBottom: theme.spacing(0.5),
}));

const NodeTitle = styled('div')<{ type: string }>(({ theme, type }: { theme: Theme; type: string }) => ({
  fontWeight: 500,
  color: theme.palette.text.primary,
  fontSize: type === 'package' ? '14px' : '12px',
  flex: 1,
  whiteSpace: 'nowrap',
  overflow: 'hidden',
  textOverflow: 'ellipsis',
}));

const NodeType = styled('div')(({ theme }: { theme: Theme }) => ({
  padding: theme.spacing(0.5, 1),
  backgroundColor: 'rgba(255, 255, 255, 0.08)',
  borderRadius: graphTheme.nodes.borderRadius,
  color: theme.palette.text.secondary,
  fontSize: '12px',
  textTransform: 'uppercase',
  letterSpacing: '0.5px',
}));

const NodeContent = styled('div')(({ theme }: { theme: Theme }) => ({
  display: 'flex',
  flexDirection: 'column',
  gap: theme.spacing(0.5),
  maxHeight: 120,
  overflowY: 'auto',
}));

const NodeSection = styled('div')(({ theme }: { theme: Theme }) => ({
  display: 'flex',
  flexDirection: 'column',
  gap: theme.spacing(0.25),
  padding: theme.spacing(0.5),
  backgroundColor: 'rgba(255, 255, 255, 0.05)',
  borderRadius: graphTheme.nodes.borderRadius,
}));

const SectionTitle = styled('div')(({ theme }: { theme: Theme }) => ({
  color: theme.palette.text.secondary,
  fontSize: '12px',
  fontWeight: 'bold',
  textTransform: 'uppercase',
  marginBottom: theme.spacing(0.25),
}));

const ItemRow = styled('div')(({ theme }: { theme: Theme }) => ({
  display: 'flex',
  alignItems: 'center',
  gap: theme.spacing(0.5),
  color: theme.palette.text.primary,
  fontSize: '12px',
  padding: theme.spacing(0.25),
  borderRadius: graphTheme.nodes.borderRadius,
  '&:hover': {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
  },
}));

const Visibility = styled('span')<{ visibility: string }>(
  ({ theme, visibility }: { theme: Theme; visibility: string }) => ({
    width: graphTheme.nodes.padding.content / 4,
    height: graphTheme.nodes.padding.content / 4,
    borderRadius: '50%',
    backgroundColor:
      visibility === 'public'
        ? theme.palette.success.main
        : visibility === 'protected'
          ? theme.palette.warning.main
          : theme.palette.error.main,
  })
);

/**
 * Dependency Node Component - displays a node in the dependency graph
 */
const DependencyNode = memo(({ id, data, selected, type }: DependencyProps) => {
  const { setNodes } = useReactFlow();
  const muiTheme = useTheme();

  // Make sure data exists and has the required properties
  const nodeData = data as DependencyData;
  const nodeType = type as DependencyKind;
  const isSelected = !!selected;

  // Safe debug logging with type checks
  console.info('DependencyNode data:', {
    id,
    type: nodeType,
    properties: nodeData.properties ?? [],
    methods: nodeData.methods ?? [],
  });

  // Handler for node resizing
  const updateNodeDimensions = useCallback(
    (_: unknown, { width, height }: { width: number; height: number }) => {
      setNodes((nds) =>
        nds.map((node) => {
          if (node.id === id) {
            return {
              ...node,
              measured: { width, height },
            };
          }
          return node;
        })
      );
    },
    [id, setNodes]
  );

  return (
    <>
      <NodeResizer
        isVisible={isSelected}
        minWidth={graphTheme.nodes.minDimensions.width}
        minHeight={graphTheme.nodes.minDimensions.height}
        handleStyle={{ backgroundColor: muiTheme.palette.primary.main }}
        lineStyle={{ border: `1px solid ${muiTheme.palette.primary.main}` }}
        onResize={updateNodeDimensions}
      />
      <NodeContainer selected={isSelected} type={nodeType}>
        <Handle type="target" position={Position.Top} />
        <NodeHeader>
          <NodeTitle type={nodeType}>{nodeData.label || 'Unnamed'}</NodeTitle>
          <NodeType>{nodeType}</NodeType>
        </NodeHeader>
        <NodeContent>
          {nodeData.properties && nodeData.properties.length > 0 ? (
            <NodeSection>
              <SectionTitle>Properties</SectionTitle>
              {nodeData.properties.map((prop: NodeProperty, index: number) => (
                <ItemRow key={index}>
                  {prop.visibility ? <Visibility visibility={prop.visibility} /> : null}
                  <span>
                    {prop.name}: {prop.type}
                  </span>
                </ItemRow>
              ))}
            </NodeSection>
          ) : null}
          {nodeData.methods && nodeData.methods.length > 0 ? (
            <NodeSection>
              <SectionTitle>Methods</SectionTitle>
              {nodeData.methods.map((method: NodeMethod, index: number) => (
                <ItemRow key={index}>
                  {method.visibility ? <Visibility visibility={method.visibility} /> : null}
                  <span>
                    {method.name}(): {method.returnType}
                  </span>
                </ItemRow>
              ))}
            </NodeSection>
          ) : null}
        </NodeContent>
        <Handle type="source" position={Position.Bottom} />
      </NodeContainer>
    </>
  );
});

DependencyNode.displayName = 'DependencyNode';

export default DependencyNode;

// packages/magus-typescript-viewer/src/client/components/DependencyGraph/nodes/DependencyNode.vue
<script setup lang="ts">
import { computed } from 'vue';

import { Handle, Position } from '@vue-flow/core';

import type { DependencyProps } from '../types';

const props = defineProps<DependencyProps>();

// Make sure data exists and has the required properties
const nodeData = computed(() => props.data);
const nodeType = computed(() => props.type);
const isSelected = computed(() => !!props.selected);

// Safe debug logging with type checks
console.info('DependencyNode data:', {
  id: props.id,
  type: nodeType.value,
  properties: nodeData.value.properties ?? [],
  methods: nodeData.value.methods ?? [],
});

// Compute visibility color
const getVisibilityColor = (visibility: string) => {
  if (visibility === 'public') return 'bg-green-500';
  if (visibility === 'protected') return 'bg-yellow-500';
  return 'bg-red-500';
};

const containerClasses = computed(() => {
  const baseClasses = [
    'relative',
    'rounded',
    'border',
    'transition-all',
    'duration-200',
    'cursor-move',
    'w-auto',
    'h-auto',
  ];

  const sizeClasses = nodeType.value === 'package' ? ['text-sm', 'p-3'] : ['text-xs', 'p-2'];

  const styleClasses = [
    'bg-background-default',
    isSelected.value ? 'border-blue-500 shadow-[0_0_0_1px_rgba(144,202,249,0.5)]' : 'border-gray-600',
  ];

  const zIndexClass = nodeType.value === 'package' ? 'z-[5]' : 'z-[1]';

  return [...baseClasses, ...sizeClasses, ...styleClasses, zIndexClass].join(' ');
});
</script>

<template>
  <div :class="containerClasses">
    <Handle type="target" :position="Position.Top" />
    
    <!-- Node Header -->
    <div class="flex items-center gap-1 border-b border-gray-600 pb-1 mb-1">
      <div
        :class="['flex-1 font-medium text-white overflow-hidden text-ellipsis whitespace-nowrap', nodeType === 'package' ? 'text-sm' : 'text-xs']"
      >
        {{ nodeData.label || 'Unnamed' }}
      </div>
      <div class="px-2 py-1 bg-white bg-opacity-10 rounded text-gray-400 text-xs uppercase tracking-wider">
        {{ nodeType }}
      </div>
    </div>

    <!-- Node Content -->
    <div class="flex flex-col gap-1 max-h-[120px] overflow-y-auto">
      <!-- Properties Section -->
      <div v-if="nodeData.properties && nodeData.properties.length > 0" class="flex flex-col gap-0.5 p-1 bg-white bg-opacity-5 rounded">
        <div class="text-gray-400 text-xs font-bold uppercase mb-0.5">Properties</div>
        <div
          v-for="(prop, index) in nodeData.properties"
          :key="index"
          class="flex items-center gap-1 text-white text-xs p-0.5 rounded hover:bg-white hover:bg-opacity-10"
        >
          <span
            v-if="prop.visibility"
            :class="['w-2 h-2 rounded-full', getVisibilityColor(prop.visibility)]"
          ></span>
          <span>{{ prop.name }}: {{ prop.type }}</span>
        </div>
      </div>

      <!-- Methods Section -->
      <div v-if="nodeData.methods && nodeData.methods.length > 0" class="flex flex-col gap-0.5 p-1 bg-white bg-opacity-5 rounded">
        <div class="text-gray-400 text-xs font-bold uppercase mb-0.5">Methods</div>
        <div
          v-for="(method, index) in nodeData.methods"
          :key="index"
          class="flex items-center gap-1 text-white text-xs p-0.5 rounded hover:bg-white hover:bg-opacity-10"
        >
          <span
            v-if="method.visibility"
            :class="['w-2 h-2 rounded-full', getVisibilityColor(method.visibility)]"
          ></span>
          <span>{{ method.name }}(): {{ method.returnType }}</span>
        </div>
      </div>
    </div>

    <Handle type="source" :position="Position.Bottom" />
  </div>
</template>
